### PR TITLE
Handle kubectl errors during ingress-nginx installation

### LINKED ISSUE #154: Handle kubectl errors in the Octopod local install script
If something went wrong with the Kind cluster errors could be very confusing, like 
```
==> waiting for ingress-controller to become ready...
Unable to connect to the server: EOF
/bin/bash: line 93: [: ==: unary operator expected
==> waiting for ingress-controller to become ready...
Unable to connect to the server: EOF
/bin/bash: line 93: [: ==: unary operator expected
```

### PR DESCRIPTION
**Pull request by AnisimoffNikita**
closes #154

### CODE REVIEW

File: octopod_local_install.sh [hunk 1]
```diff
@@ -90,8 +90,25 @@ data:
...
+        err_code=$?
+        set -e
+        if [ $err_code != 0 ] && [ $has_error == 0 ]; then
+                echo "kubectl returned: $kube_out"
+                echo "Do you want to continue installation? [y/n] "
+                read confirm
+                if [ "$confirm" != 'y' ]; then
+                        message "Deleting cluster..."
+                        kind delete cluster --name octopod
+                        exit 0;
```
Comment (ilyakooo0) [inline octopod_local_install.sh:106]: We delete the cluster and exit if the user wants to continue?

**Review by ilyakooo0 — CHANGES_REQUESTED** [review]

File: octopod_local_install.sh (hunk 1 above)
Comment (AnisimoffNikita) [reply octopod_local_install.sh:106]: there is `!=`
we delete it when user inputs something different than `y`

Comment (ilyakooo0) [reply octopod_local_install.sh:106]: oh, sorry (:

**Review by ilyakooo0 — APPROVED** [review]
